name: waywatch_app
description: "A family location sharing app with modern Material 3 design."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0
  flutter_otp_text_field: ^1.1.1
  intl: ^0.19.0
  uuid: ^4.3.3
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
 # assets:
  #  - assets/images/
   # - assets/animations/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
