// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:848570118368:web:4a0078ed8a861bdfb96085',
    messagingSenderId: '848570118368',
    projectId: 'waywatch0',
    authDomain: 'waywatch0.firebaseapp.com',
    storageBucket: 'waywatch0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:848570118368:android:e68bd3f7f6e19d6db96085',
    messagingSenderId: '848570118368',
    projectId: 'waywatch0',
    storageBucket: 'waywatch0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:848570118368:ios:50d018cdfdb12e3ab96085',
    messagingSenderId: '848570118368',
    projectId: 'waywatch0',
    storageBucket: 'waywatch0.firebasestorage.app',
    iosBundleId: 'com.example.waywatch0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHl0fcNfDh6QONHjxnodQwvkoggxcubE',
    appId: '1:848570118368:ios:50d018cdfdb12e3ab96085',
    messagingSenderId: '848570118368',
    projectId: 'waywatch0',
    storageBucket: 'waywatch0.firebasestorage.app',
    iosBundleId: 'com.example.waywatch0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALJyyWX4n1ilweLWxLTOvqgy0GXHFb7z8',
    appId: '1:848570118368:web:fa7b64fb44cde7deb96085',
    messagingSenderId: '848570118368',
    projectId: 'waywatch0',
    authDomain: 'waywatch0.firebaseapp.com',
    storageBucket: 'waywatch0.firebasestorage.app',
  );
}
